### ISSUE TITLE
Library Import Error

### ISSUE THREAD

**Issue by animeshsrivastava24** [per1234/ThemeTest#1]
Following the procedure of "ThemeTest" on Arduino Software installed on Linux Ubuntu System, both with normal and sudo methods of launching the software. I land with the following error.
 
![Issue1](https://user-images.githubusercontent.com/24613239/58510018-7b58ed80-81b5-11e9-9f18-d3c6bed20922.png)
The Library ThemeTest-master cannot be used. Library names must contain only basic letters and numbers, (ASCII only and no spaces, and it cannot start with a number)"

The problem is since the Github “releases” contains all dashes, and Arduino prohibits them. We have to rename the folder.

**Comment by per1234** [comment]
This error means you're using an extremely outdated version of the Arduino IDE. This may have been caused by you using `apt install arduino` to install the Arduino IDE. You should always download the official Arduino IDE from:
https://www.arduino.cc/en/Main/Software
The versions of the Arduino IDE you get from package managers will tend to be outdated and modified by 3rd parties in unspecified ways.

If you do prefer to use the ancient IDE version for some reason, just rename the folder so that it doesn't contain the previously disallowed characters.

**Comment by animeshsrivastava24** [comment]
Yes, I updated to the official version and the error is fixed.  @per1234 .

**Comment by animeshsrivastava24** [comment]
@per1234  Please help me with an initial task to begin with, as mentioned on  https://github.com/arduino/season-of-docs/blob/master/IDEAS.md. It will be of a great help,

> The project is to create a user-friendly guide to:
>   - The purpose of each theme property
>   - Customizing button graphics files
>   - Installing custom themes

**Comment by per1234** [comment]
@animeshsrivastava24 thanks so much for your interest in contributing to this project!

https://github.com/arduino/season-of-docs/blob/master/IDEAS.md is related to the Arduino's participation in the Google Season of Docs program:
https://developers.google.com/season-of-docs/

If you want to work on this project as a technical writer in the Season of Docs program, you will need to go through the application process of that program. Technical writer applications are due 2019-06-28. The documentation development process for Season of Docs doesn't start until 2019-11-02 (see the timeline [here](https://developers.google.com/season-of-docs/docs/timeline)). If you have any questions specific to the Season of Docs program, please email them to season-of-docs@arduino.cc

If you want to contribute to the Arduino IDE theme documentation as a volunteer not associated with the Season of Docs program, that is very welcome as well!

So please let me know whether you are wanting to be a Season of Docs technical writer, or just want to contribute some documentation as a volunteer.

**Comment by animeshsrivastava24** [comment]
@per1234 Yes, I'm targeting Season of Docs Technical Writer and looking for writing and documenting the ideas mentioned. I've subscribed to the mailing list for the same. 

Is it possible to document and create a Wiki for each functioning element in the theme that can be modified and providing various images along with the same, we can expand the contents provided in the Readme.md .
Please guide .

**Comment by per1234** [comment]
>I'm targeting Season of Docs Technical Writer

Great! It's a wonderful program. I'm one of the mentors for it and am happy to help out the prospective technical writers in any way I can.

For the Season of Docs "Document the Arduino IDE's themes system" project, the documentation the technical writer produces will be published to Arduino's GitHub wiki by the end of the program:
https://github.com/arduino/Arduino/wiki
The GitHub wiki contains Arduino's developer targeted documentation, while arduino.cc contains the user targeted documentation. Since the theme documentation will be used by theme developers, the GitHub wiki seems the most appropriate location to publish that documentation.

That wiki is publicly editable so it's very easy to publish content there and for anyone to make corrections or updates as needed. It is much more difficult and less efficient to publish or update content on arduino.cc so this is another advantage of using the GitHub wiki.

The existing documentation in my ThemeTest repository will only act as a starting point and reference for the Season of Docs technical writer. The documentation produced during the Season of Docs program will not be published to my ThemeTest repository. Once Arduino has official documentation of the Arduino IDE themes I will replace the documentation in my ThemeTest repository's readme with a link to the official documentation page.

**Comment by animeshsrivastava24** [comment]
@per1234  Thank you so much. I will go through each requirement, and start contributing to the Technical Writer requirement and help the community.
